### ISSUE TITLE
Liquid color coding looks nothing like the screenshot

### ISSUE THREAD

**Issue by brady-sewall** [OlegKrechkovskiy/cobalt-liquid#1]
The liquid color coding in your screenshot looks very useful! However, when I apply the theme, it does not look like the screenshot. Any suggestions?
![image](https://github.com/OlegKrechkovskiy/cobalt-liquid/assets/38672484/245d5b46-e0f0-4dba-b909-f42b8a0a48db)

**Comment by OlegKrechkovskiy** [comment]
Hi! please tell me which language is defined in the editor you have?
![image](https://github.com/OlegKrechkovskiy/cobalt-liquid/assets/43177655/867ec09a-0b11-43ef-a0a0-d312478b32a4)
